# Generated by Django 3.1.5 on 2021-07-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='created_by',
        ),
    ]
