# Generated by Django 3.1.5 on 2021-07-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorized_user', '0002_auto_20210710_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='IH',
        ),
    ]
