# Generated by Django 3.1.5 on 2021-07-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_analyser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadet_bio',
            name='id',
        ),
        migrations.AlterField(
            model_name='cadet_bio',
            name='C_N',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
